### ISSUE TITLE
Gracefully pass cycle if selected tweet has already been retweeted

### ISSUE THREAD

**Issue by thornjad** [thornjad/jtbot#10]
Showed up in a CI build in #9

**Comment by thornjad** [comment]
CI spit out:

```
Retweet run done, waiting for next
Unable to retweet
/home/travis/build/Raindeer44/jade-bot/lib/retweet.js:41
              throw err;
              ^
Error: You have already retweeted this tweet.
    at Object.exports.makeTwitError (/home/travis/build/Raindeer44/jade-bot/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/home/travis/build/Raindeer44/jade-bot/node_modules/twit/lib/twitter.js:328:25)
    at Request.<anonymous> (/home/travis/build/Raindeer44/jade-bot/node_modules/twit/lib/twitter.js:348:7)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/home/travis/build/Raindeer44/jade-bot/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! Test failed.  See above for more details.
```
